### PR TITLE
Implements a ReaderT example for "interpret"

### PR DESCRIPTION
**Pull request by kritzcreek**
The `Env` here allows us to configure a Github token to use for authorization when making the requests.

- Do we need comments or explanations in here, or should they go in a GUIDE chapter instead?
- Do we want a "TestM" type that mocks the request?
- Do we want to make the Github user name into an input field instead? (Would make the Action type more complicated but the example a little more interesting)

### CODE REVIEW

**Comment by garyb** [comment]
I like to keep the examples showing one new thing at a time really, so I think this is doing more stuff than it needs to - I'd just exactly use `ReaderT _ Aff` rather than having a newtype, and wouldn't have the `GithubAPI` class in there or anything. The realworld stuff is a much better place for going into those kinds of usages I think.

Either that or split it into two examples perhaps - `interpret-reader` and `interpret-constraints` or something like that.

**Comment by kritzcreek** [comment]
> I'd just exactly use `ReaderT _ Aff`

That would lose expressiveness compared to the previous `Free` example, but it would show the simplest case of using a different `m` for a component with `hoist`. I guess we can stretch `interpret` to that meaning.

**Comment by garyb** [comment]
Yeah, I think that's good enough. I just put the `Free` stuff in there before because we weren't using `hoist` at all at that point, and it was just something that would work in there - I hadn't thought of `ReaderT`.

I'm not sure this function should be called `hoist` too, since I don't think it's truly a `hoist`.

**Comment by kritzcreek** [comment]
AFAICT now only the `todo` example is missing.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
