### PR TITLE
Queue messages until component has initialized

### PR DESCRIPTION
**Pull request by garyb**
@natefaubion Here's the sequence reported from the `Lifecycle` example now when adding:

```
Ref Cell 0
Ref Cell 1
Ref Cell 2
Ref Child 0
Initialize Cell 0
Initialize Cell 1
Initialize Cell 2
Initialize Child 0
Child 0 >>> Heard Refd from cell0
Child 0 >>> Heard Initialized from cell0
Child 0 >>> Heard Refd from cell1
Child 0 >>> Heard Initialized from cell1
Child 0 >>> Heard Refd from cell2
Child 0 >>> Heard Initialized from cell2
Root >>> Heard Refd from child0
Root >>> Heard Initialized from child0
Root >>> Re-reporting from child0: Heard Refd from cell0
Root >>> Re-reporting from child0: Heard Initialized from cell0
Root >>> Re-reporting from child0: Heard Refd from cell1
Root >>> Re-reporting from child0: Heard Initialized from cell1
Root >>> Re-reporting from child0: Heard Refd from cell2
Root >>> Re-reporting from child0: Heard Initialized from cell2
```

The queuing works in two places:
1. a component will not emit any messages of its own until it has initialized
2. a component will not handle any messages from a child until it has initialzed

And things are handled in that order too, so in the log above you can see the messages `raise`d from the child are heard at the root before the messages that were originally raised by a cell.

Does that seem sensible? It kinda doesn't matter which way round the queues are processed, we could emit the messages that arose before init for a component first and it would still work out, because either way, if you hear a message from a component then you know it has initialized, so querying it is safe.

### CODE REVIEW

**Comment by natefaubion** [comment]
I think this makes sense. 👍 

I see `sequence`s and it makes me a little leery, but I'm not sure how these messages are resolved. Are the processed in order, like one has to complete before the next runs, or does it effectively end up forked at some point? Aff makes it very easy to make things unnecessarily blocking, so I think we should be explicit with forking if that's the intention. The example is also completely synchronous so any problem cases wouldn't show up.

**Comment by garyb** [comment]
Yeah, I know what you mean - having async stuff in here would indeed be a can of worms, but I'm not sure `fork`ing each handler / `parTraverse`ing is right here either? I don't really know.

It's a bit strange, because if you do that you're guaranteed to have multiples queries executing on a component in parallel (in the case above I mean, where `Ref` and `Initialize` from cells 0-2 would be handled by child 0 "at the same time")... but then if we weren't queuing I guess there's nothing to stop that from happening, because that's how the messaging works (like if a child `raises` 3 things in an `eval`, 3 queries will be raised on the parent, and would run in parallel if async).

**Comment by garyb** [comment]
So I think it probably is "more right" than `sequence`. What do you think then, `fork` each `pending` thing?

**Comment by natefaubion** [comment]
Right, there's always the chance that multiple queries can be running at the same time (I'd say it's guaranteed to happen if you do something as _dangerous_ as HTTP calls). While they are "parallel", there is a defined ordering to them, and that's what matters. So we should _always_ take care to not execute things one-after-the-other since it's possible that one may never even complete! Forking is the correct behavior.

**Comment by natefaubion** [comment]
I guess _technically_ the ordering should still be "undefined", though there is an observable ordering.

**Comment by garyb** [comment]
There's one `sequence` left, and this one I'm not sure about: https://github.com/garyb/purescript-halogen/blob/ac54b70cb3e657cdbca96922514bb4230555943b/src/Halogen/Aff/Driver.purs#L66

Maybe the whole thing should be forked, but not each individual initializer, as here the order really does matter, since we don't want to initialize a component that has children that are not yet initialized. I don't know. If the initializers as synchronous it doesn't matter either way, but unless we say they _must_ be for things to behave as expected, I think `sequence` might be the right thing here?

**Comment by natefaubion** [comment]
I don't think you want to `sequence` there, though. I think you want to fork finalizers _first_ (that way you cleanup the old before introducing anything new), and then you'd want to do something with `parTraverse_`.

**Comment by garyb** [comment]
Agreed on moving the finalizers up - but I'm still not sure about `parTraverse`, you can (potentially) have parents initialize before their children if you do that, which is currently avoided.

**Comment by natefaubion** [comment]
The goal would be to run all child initializers in parallel, and then once those complete run the parent initializer. It may not be setup that way currently, but I don't think you want to only run one child initializer at a time unless you can enforce synchronous semantics on the initializer (which we currently can't do). You could potentially do this if you had a separate (framework provided) algebra for lifecycle events.

**Comment by garyb** [comment]
Yeah, you're right, that definitely would be the ideal. I'll have a think, it might not be too hard to make happen.

**Pull request merged**
